Repository TileDB-Inc/TileDB-ML, pull requests merged in 2021-06, with the labels that each got.

#41 [Enhancement] Implemented __len__() for TF and PyTorch Dense APIs Support
  tests/test_pytorch_dataloader_api.py
  tests/test_tensorflow_data_api.py
  tiledb/ml/data_apis/pytorch.py
  tiledb/ml/data_apis/tensorflow.py
Labels: enhancement

#42 Update tensorflow version to 2.5
  requirements.txt
  setup.py
Labels: enhancement

#40 [Feature] Example on the use of TensorflowTileDBDenseDataset Class
  examples/data_apis/tensorflow_data_api_tiledb_dense.ipynb
Labels: documentation

#37 [BugFix] Checking row dimension between x and y
  tests/test_pytorch_sparse_dataloader_api.py
  tiledb/ml/data_apis/pytorch_sparse.py
Labels: bug

#35 [Feature] Example PyTorch Sparse Data Api - TileDB Sparse Array
  examples/data_apis/pytorch_data_api_tiledb_sparse.ipynb
Labels: documentation

#43 [BugFix] Checking row dimension between x and y for TF implementation
  tests/test_tensorflow_sparse_data_api.py
  tiledb/ml/data_apis/tensorflow_sparse.py
Labels: bug

#44 [Feature] Example Tensorflow Sparse Data Api - TileDB Sparse Array
  examples/data_apis/tensorflow_data_api_tiledb_sparse.ipynb
Labels: documentation

#45 Readme update
  README.md
Labels: documentation

#49 [Enhancement] Run tests with PyTest
  .github/workflows/ci.yml
  README.md
  requirements.txt
  setup.py
  tests/test_pytorch_dataloader_api.py
  tests/test_pytorch_models.py
  tests/test_pytorch_sparse_dataloader_api.py
  tests/test_sklearn_models.py
  tests/test_tensorflow_data_api.py
  tests/test_tensorflow_keras_models.py
  tests/test_tensorflow_sparse_data_api.py
  tiledb/ml/_utils.py
Labels: enhancement

#50 [Enhancement] Adding test coverage stats and repo badges
  .github/workflows/ci.yml
  README.md
Labels: enhancement

#54 Register ML model with TileDB Cloud - Tensorflow&&PyTorch
  examples/cloud/pytorch_tiledb_cloud_ml_model_array.ipynb
  examples/cloud/sklearn_tiledb_cloud_ml_model_array.ipynb
  examples/cloud/tensorflow_tiledb_cloud_ml_model_array.ipynb
  tiledb/ml/models/pytorch.py
  tiledb/ml/models/sklearn.py
  tiledb/ml/models/tensorflow.py
Labels: enhancement

#56 [Hotfix] Fixing cloud import in models base
  tiledb/ml/models/base.py
Labels: bug

#55 Load models at specific timestamp
  setup.py
  tiledb/ml/models/pytorch.py
  tiledb/ml/models/sklearn.py
  tiledb/ml/models/tensorflow.py
Labels: enhancement

#57 [Enhancement] Prepare Release Tiledb-ML in PyPi and CI job
  .github/workflows/release.yml
  README.md
  setup.cfg
  setup.py
  tiledb/ml/_cloud_utils.py
  tiledb/ml/models/pytorch.py
  tiledb/ml/models/sklearn.py
  tiledb/ml/models/tensorflow.py
Labels: bug, enhancement

#60 [Feature] Changes for supporting model preview for all frameworks
  tests/test_pytorch_models.py
  tests/test_sklearn_models.py
  tests/test_tensorflow_keras_models.py
  tiledb/ml/models/base.py
  tiledb/ml/models/pytorch.py
  tiledb/ml/models/sklearn.py
  tiledb/ml/models/tensorflow.py
Labels: enhancement
